plugins:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Include:
    - 'skills/*/scripts/*.rb'
    - 'scripts/*.rb'
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'scripts/signalshelf_notify.rb'

Metrics/AbcSize:
  Max: 35
  Exclude:
    - 'scripts/signalshelf_notify.rb'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'scripts/signalshelf_notify.rb'

Metrics/PerceivedComplexity:
  Max: 12
  Exclude:
    - 'scripts/signalshelf_notify.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'scripts/signalshelf_notify.rb'

Metrics/ParameterLists:
  Exclude:
    - 'scripts/signalshelf_notify.rb'

Lint/DuplicateBranch:
  Exclude:
    - 'scripts/signalshelf_notify.rb'
